// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"fmt"
	"strings"
)

const (
	// CronKeyFetchArticle is a CronKey of type fetch_article.
	// 爬取文章
	CronKeyFetchArticle CronKey = "fetch_article"
)

var ErrInvalidCronKey = fmt.Errorf("not a valid CronKey, try [%s]", strings.Join(_CronKeyNames, ", "))

var _CronKeyNames = []string{
	string(CronKeyFetchArticle),
}

// CronKeyNames returns a list of possible string values of CronKey.
func CronKeyNames() []string {
	tmp := make([]string, len(_CronKeyNames))
	copy(tmp, _CronKeyNames)
	return tmp
}

// CronKeyValues returns a list of the values for CronKey
func CronKeyValues() []CronKey {
	return []CronKey{
		CronKeyFetchArticle,
	}
}

// String implements the Stringer interface.
func (x CronKey) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CronKey) IsValid() bool {
	_, err := ParseCronKey(string(x))
	return err == nil
}

var _CronKeyValue = map[string]CronKey{
	"fetch_article": CronKeyFetchArticle,
}

// ParseCronKey attempts to convert a string to a CronKey.
func ParseCronKey(name string) (CronKey, error) {
	if x, ok := _CronKeyValue[name]; ok {
		return x, nil
	}
	return CronKey(""), fmt.Errorf("%s is %w", name, ErrInvalidCronKey)
}

// MustParseCronKey converts a string to a CronKey, and panics if is not valid.
func MustParseCronKey(name string) CronKey {
	val, err := ParseCronKey(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x CronKey) Ptr() *CronKey {
	return &x
}
