// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"fmt"
	"strings"
)

const (
	// DistributionStatusPending is a DistributionStatus of type pending.
	// 待发放
	DistributionStatusPending DistributionStatus = "pending"
	// DistributionStatusDistributing is a DistributionStatus of type distributing.
	// 发放中
	DistributionStatusDistributing DistributionStatus = "distributing"
	// DistributionStatusFailed is a DistributionStatus of type failed.
	// 发放失败
	DistributionStatusFailed DistributionStatus = "failed"
	// DistributionStatusSuccess is a DistributionStatus of type success.
	// 发放成功
	DistributionStatusSuccess DistributionStatus = "success"
)

var ErrInvalidDistributionStatus = fmt.Errorf("not a valid DistributionStatus, try [%s]", strings.Join(_DistributionStatusNames, ", "))

var _DistributionStatusNames = []string{
	string(DistributionStatusPending),
	string(DistributionStatusDistributing),
	string(DistributionStatusFailed),
	string(DistributionStatusSuccess),
}

// DistributionStatusNames returns a list of possible string values of DistributionStatus.
func DistributionStatusNames() []string {
	tmp := make([]string, len(_DistributionStatusNames))
	copy(tmp, _DistributionStatusNames)
	return tmp
}

// DistributionStatusValues returns a list of the values for DistributionStatus
func DistributionStatusValues() []DistributionStatus {
	return []DistributionStatus{
		DistributionStatusPending,
		DistributionStatusDistributing,
		DistributionStatusFailed,
		DistributionStatusSuccess,
	}
}

// String implements the Stringer interface.
func (x DistributionStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DistributionStatus) IsValid() bool {
	_, err := ParseDistributionStatus(string(x))
	return err == nil
}

var _DistributionStatusValue = map[string]DistributionStatus{
	"pending":      DistributionStatusPending,
	"distributing": DistributionStatusDistributing,
	"failed":       DistributionStatusFailed,
	"success":      DistributionStatusSuccess,
}

// ParseDistributionStatus attempts to convert a string to a DistributionStatus.
func ParseDistributionStatus(name string) (DistributionStatus, error) {
	if x, ok := _DistributionStatusValue[name]; ok {
		return x, nil
	}
	return DistributionStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidDistributionStatus)
}

// MustParseDistributionStatus converts a string to a DistributionStatus, and panics if is not valid.
func MustParseDistributionStatus(name string) DistributionStatus {
	val, err := ParseDistributionStatus(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x DistributionStatus) Ptr() *DistributionStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x DistributionStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *DistributionStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseDistributionStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
