// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"fmt"
	"strings"
)

const (
	// VoteLogValidValid is a VoteLogValid of type valid.
	// 有效
	VoteLogValidValid VoteLogValid = "valid"
	// VoteLogValidInvalid is a VoteLogValid of type invalid.
	// 无效
	VoteLogValidInvalid VoteLogValid = "invalid"
)

var ErrInvalidVoteLogValid = fmt.Errorf("not a valid VoteLogValid, try [%s]", strings.Join(_VoteLogValidNames, ", "))

var _VoteLogValidNames = []string{
	string(VoteLogValidValid),
	string(VoteLogValidInvalid),
}

// VoteLogValidNames returns a list of possible string values of VoteLogValid.
func VoteLogValidNames() []string {
	tmp := make([]string, len(_VoteLogValidNames))
	copy(tmp, _VoteLogValidNames)
	return tmp
}

// VoteLogValidValues returns a list of the values for VoteLogValid
func VoteLogValidValues() []VoteLogValid {
	return []VoteLogValid{
		VoteLogValidValid,
		VoteLogValidInvalid,
	}
}

// String implements the Stringer interface.
func (x VoteLogValid) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x VoteLogValid) IsValid() bool {
	_, err := ParseVoteLogValid(string(x))
	return err == nil
}

var _VoteLogValidValue = map[string]VoteLogValid{
	"valid":   VoteLogValidValid,
	"invalid": VoteLogValidInvalid,
}

// ParseVoteLogValid attempts to convert a string to a VoteLogValid.
func ParseVoteLogValid(name string) (VoteLogValid, error) {
	if x, ok := _VoteLogValidValue[name]; ok {
		return x, nil
	}
	return VoteLogValid(""), fmt.Errorf("%s is %w", name, ErrInvalidVoteLogValid)
}

// MustParseVoteLogValid converts a string to a VoteLogValid, and panics if is not valid.
func MustParseVoteLogValid(name string) VoteLogValid {
	val, err := ParseVoteLogValid(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x VoteLogValid) Ptr() *VoteLogValid {
	return &x
}

// MarshalText implements the text marshaller method.
func (x VoteLogValid) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *VoteLogValid) UnmarshalText(text []byte) error {
	tmp, err := ParseVoteLogValid(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// VoteTypeNormal is a VoteType of type normal.
	// 普通投票
	VoteTypeNormal VoteType = "normal"
	// VoteTypeJury is a VoteType of type jury.
	// 评审团投票
	VoteTypeJury VoteType = "jury"
)

var ErrInvalidVoteType = fmt.Errorf("not a valid VoteType, try [%s]", strings.Join(_VoteTypeNames, ", "))

var _VoteTypeNames = []string{
	string(VoteTypeNormal),
	string(VoteTypeJury),
}

// VoteTypeNames returns a list of possible string values of VoteType.
func VoteTypeNames() []string {
	tmp := make([]string, len(_VoteTypeNames))
	copy(tmp, _VoteTypeNames)
	return tmp
}

// VoteTypeValues returns a list of the values for VoteType
func VoteTypeValues() []VoteType {
	return []VoteType{
		VoteTypeNormal,
		VoteTypeJury,
	}
}

// String implements the Stringer interface.
func (x VoteType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x VoteType) IsValid() bool {
	_, err := ParseVoteType(string(x))
	return err == nil
}

var _VoteTypeValue = map[string]VoteType{
	"normal": VoteTypeNormal,
	"jury":   VoteTypeJury,
}

// ParseVoteType attempts to convert a string to a VoteType.
func ParseVoteType(name string) (VoteType, error) {
	if x, ok := _VoteTypeValue[name]; ok {
		return x, nil
	}
	return VoteType(""), fmt.Errorf("%s is %w", name, ErrInvalidVoteType)
}

// MustParseVoteType converts a string to a VoteType, and panics if is not valid.
func MustParseVoteType(name string) VoteType {
	val, err := ParseVoteType(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x VoteType) Ptr() *VoteType {
	return &x
}

// MarshalText implements the text marshaller method.
func (x VoteType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *VoteType) UnmarshalText(text []byte) error {
	tmp, err := ParseVoteType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
