// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"fmt"
	"strings"
)

const (
	// VoteJuryApplyLogStatusPending is a VoteJuryApplyLogStatus of type pending.
	// 待审核
	VoteJuryApplyLogStatusPending VoteJuryApplyLogStatus = "pending"
	// VoteJuryApplyLogStatusApproved is a VoteJuryApplyLogStatus of type approved.
	// 已通过
	VoteJuryApplyLogStatusApproved VoteJuryApplyLogStatus = "approved"
	// VoteJuryApplyLogStatusRejected is a VoteJuryApplyLogStatus of type rejected.
	// 已拒绝
	VoteJuryApplyLogStatusRejected VoteJuryApplyLogStatus = "rejected"
)

var ErrInvalidVoteJuryApplyLogStatus = fmt.Errorf("not a valid VoteJuryApplyLogStatus, try [%s]", strings.Join(_VoteJuryApplyLogStatusNames, ", "))

var _VoteJuryApplyLogStatusNames = []string{
	string(VoteJuryApplyLogStatusPending),
	string(VoteJuryApplyLogStatusApproved),
	string(VoteJuryApplyLogStatusRejected),
}

// VoteJuryApplyLogStatusNames returns a list of possible string values of VoteJuryApplyLogStatus.
func VoteJuryApplyLogStatusNames() []string {
	tmp := make([]string, len(_VoteJuryApplyLogStatusNames))
	copy(tmp, _VoteJuryApplyLogStatusNames)
	return tmp
}

// VoteJuryApplyLogStatusValues returns a list of the values for VoteJuryApplyLogStatus
func VoteJuryApplyLogStatusValues() []VoteJuryApplyLogStatus {
	return []VoteJuryApplyLogStatus{
		VoteJuryApplyLogStatusPending,
		VoteJuryApplyLogStatusApproved,
		VoteJuryApplyLogStatusRejected,
	}
}

// String implements the Stringer interface.
func (x VoteJuryApplyLogStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x VoteJuryApplyLogStatus) IsValid() bool {
	_, err := ParseVoteJuryApplyLogStatus(string(x))
	return err == nil
}

var _VoteJuryApplyLogStatusValue = map[string]VoteJuryApplyLogStatus{
	"pending":  VoteJuryApplyLogStatusPending,
	"approved": VoteJuryApplyLogStatusApproved,
	"rejected": VoteJuryApplyLogStatusRejected,
}

// ParseVoteJuryApplyLogStatus attempts to convert a string to a VoteJuryApplyLogStatus.
func ParseVoteJuryApplyLogStatus(name string) (VoteJuryApplyLogStatus, error) {
	if x, ok := _VoteJuryApplyLogStatusValue[name]; ok {
		return x, nil
	}
	return VoteJuryApplyLogStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidVoteJuryApplyLogStatus)
}

// MustParseVoteJuryApplyLogStatus converts a string to a VoteJuryApplyLogStatus, and panics if is not valid.
func MustParseVoteJuryApplyLogStatus(name string) VoteJuryApplyLogStatus {
	val, err := ParseVoteJuryApplyLogStatus(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x VoteJuryApplyLogStatus) Ptr() *VoteJuryApplyLogStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x VoteJuryApplyLogStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *VoteJuryApplyLogStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseVoteJuryApplyLogStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// VoteJuryRuleStatusPending is a VoteJuryRuleStatus of type pending.
	// 未开启
	VoteJuryRuleStatusPending VoteJuryRuleStatus = "pending"
	// VoteJuryRuleStatusApplying is a VoteJuryRuleStatus of type applying.
	// 申请中
	VoteJuryRuleStatusApplying VoteJuryRuleStatus = "applying"
	// VoteJuryRuleStatusPublicity is a VoteJuryRuleStatus of type publicity.
	// 公示中
	VoteJuryRuleStatusPublicity VoteJuryRuleStatus = "publicity"
	// VoteJuryRuleStatusVoting is a VoteJuryRuleStatus of type voting.
	// 评审中
	VoteJuryRuleStatusVoting VoteJuryRuleStatus = "voting"
	// VoteJuryRuleStatusCompleted is a VoteJuryRuleStatus of type completed.
	// 计票完成
	VoteJuryRuleStatusCompleted VoteJuryRuleStatus = "completed"
)

var ErrInvalidVoteJuryRuleStatus = fmt.Errorf("not a valid VoteJuryRuleStatus, try [%s]", strings.Join(_VoteJuryRuleStatusNames, ", "))

var _VoteJuryRuleStatusNames = []string{
	string(VoteJuryRuleStatusPending),
	string(VoteJuryRuleStatusApplying),
	string(VoteJuryRuleStatusPublicity),
	string(VoteJuryRuleStatusVoting),
	string(VoteJuryRuleStatusCompleted),
}

// VoteJuryRuleStatusNames returns a list of possible string values of VoteJuryRuleStatus.
func VoteJuryRuleStatusNames() []string {
	tmp := make([]string, len(_VoteJuryRuleStatusNames))
	copy(tmp, _VoteJuryRuleStatusNames)
	return tmp
}

// VoteJuryRuleStatusValues returns a list of the values for VoteJuryRuleStatus
func VoteJuryRuleStatusValues() []VoteJuryRuleStatus {
	return []VoteJuryRuleStatus{
		VoteJuryRuleStatusPending,
		VoteJuryRuleStatusApplying,
		VoteJuryRuleStatusPublicity,
		VoteJuryRuleStatusVoting,
		VoteJuryRuleStatusCompleted,
	}
}

// String implements the Stringer interface.
func (x VoteJuryRuleStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x VoteJuryRuleStatus) IsValid() bool {
	_, err := ParseVoteJuryRuleStatus(string(x))
	return err == nil
}

var _VoteJuryRuleStatusValue = map[string]VoteJuryRuleStatus{
	"pending":   VoteJuryRuleStatusPending,
	"applying":  VoteJuryRuleStatusApplying,
	"publicity": VoteJuryRuleStatusPublicity,
	"voting":    VoteJuryRuleStatusVoting,
	"completed": VoteJuryRuleStatusCompleted,
}

// ParseVoteJuryRuleStatus attempts to convert a string to a VoteJuryRuleStatus.
func ParseVoteJuryRuleStatus(name string) (VoteJuryRuleStatus, error) {
	if x, ok := _VoteJuryRuleStatusValue[name]; ok {
		return x, nil
	}
	return VoteJuryRuleStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidVoteJuryRuleStatus)
}

// MustParseVoteJuryRuleStatus converts a string to a VoteJuryRuleStatus, and panics if is not valid.
func MustParseVoteJuryRuleStatus(name string) VoteJuryRuleStatus {
	val, err := ParseVoteJuryRuleStatus(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x VoteJuryRuleStatus) Ptr() *VoteJuryRuleStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x VoteJuryRuleStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *VoteJuryRuleStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseVoteJuryRuleStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// VoteJuryUserStatusPending is a VoteJuryUserStatus of type pending.
	// 待审核
	VoteJuryUserStatusPending VoteJuryUserStatus = "pending"
	// VoteJuryUserStatusApproved is a VoteJuryUserStatus of type approved.
	// 已通过
	VoteJuryUserStatusApproved VoteJuryUserStatus = "approved"
	// VoteJuryUserStatusRejected is a VoteJuryUserStatus of type rejected.
	// 已拒绝
	VoteJuryUserStatusRejected VoteJuryUserStatus = "rejected"
)

var ErrInvalidVoteJuryUserStatus = fmt.Errorf("not a valid VoteJuryUserStatus, try [%s]", strings.Join(_VoteJuryUserStatusNames, ", "))

var _VoteJuryUserStatusNames = []string{
	string(VoteJuryUserStatusPending),
	string(VoteJuryUserStatusApproved),
	string(VoteJuryUserStatusRejected),
}

// VoteJuryUserStatusNames returns a list of possible string values of VoteJuryUserStatus.
func VoteJuryUserStatusNames() []string {
	tmp := make([]string, len(_VoteJuryUserStatusNames))
	copy(tmp, _VoteJuryUserStatusNames)
	return tmp
}

// VoteJuryUserStatusValues returns a list of the values for VoteJuryUserStatus
func VoteJuryUserStatusValues() []VoteJuryUserStatus {
	return []VoteJuryUserStatus{
		VoteJuryUserStatusPending,
		VoteJuryUserStatusApproved,
		VoteJuryUserStatusRejected,
	}
}

// String implements the Stringer interface.
func (x VoteJuryUserStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x VoteJuryUserStatus) IsValid() bool {
	_, err := ParseVoteJuryUserStatus(string(x))
	return err == nil
}

var _VoteJuryUserStatusValue = map[string]VoteJuryUserStatus{
	"pending":  VoteJuryUserStatusPending,
	"approved": VoteJuryUserStatusApproved,
	"rejected": VoteJuryUserStatusRejected,
}

// ParseVoteJuryUserStatus attempts to convert a string to a VoteJuryUserStatus.
func ParseVoteJuryUserStatus(name string) (VoteJuryUserStatus, error) {
	if x, ok := _VoteJuryUserStatusValue[name]; ok {
		return x, nil
	}
	return VoteJuryUserStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidVoteJuryUserStatus)
}

// MustParseVoteJuryUserStatus converts a string to a VoteJuryUserStatus, and panics if is not valid.
func MustParseVoteJuryUserStatus(name string) VoteJuryUserStatus {
	val, err := ParseVoteJuryUserStatus(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x VoteJuryUserStatus) Ptr() *VoteJuryUserStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x VoteJuryUserStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *VoteJuryUserStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseVoteJuryUserStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
