// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"fmt"
	"strings"
)

const (
	// UserRoleAdmin is a UserRole of type admin.
	// 管理员
	UserRoleAdmin UserRole = "admin"
	// UserRoleUser is a UserRole of type user.
	// 普通用户
	UserRoleUser UserRole = "user"
)

var ErrInvalidUserRole = fmt.Errorf("not a valid UserRole, try [%s]", strings.Join(_UserRoleNames, ", "))

var _UserRoleNames = []string{
	string(UserRoleAdmin),
	string(UserRoleUser),
}

// UserRoleNames returns a list of possible string values of UserRole.
func UserRoleNames() []string {
	tmp := make([]string, len(_UserRoleNames))
	copy(tmp, _UserRoleNames)
	return tmp
}

// UserRoleValues returns a list of the values for UserRole
func UserRoleValues() []UserRole {
	return []UserRole{
		UserRoleAdmin,
		UserRoleUser,
	}
}

// String implements the Stringer interface.
func (x UserRole) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x UserRole) IsValid() bool {
	_, err := ParseUserRole(string(x))
	return err == nil
}

var _UserRoleValue = map[string]UserRole{
	"admin": UserRoleAdmin,
	"user":  UserRoleUser,
}

// ParseUserRole attempts to convert a string to a UserRole.
func ParseUserRole(name string) (UserRole, error) {
	if x, ok := _UserRoleValue[name]; ok {
		return x, nil
	}
	return UserRole(""), fmt.Errorf("%s is %w", name, ErrInvalidUserRole)
}

// MustParseUserRole converts a string to a UserRole, and panics if is not valid.
func MustParseUserRole(name string) UserRole {
	val, err := ParseUserRole(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x UserRole) Ptr() *UserRole {
	return &x
}

// MarshalText implements the text marshaller method.
func (x UserRole) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *UserRole) UnmarshalText(text []byte) error {
	tmp, err := ParseUserRole(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
