// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"fmt"
	"strings"
)

const (
	// ActivityTemplateArticle is a ActivityTemplate of type article.
	// 征文活动
	ActivityTemplateArticle ActivityTemplate = "article"
	// ActivityTemplateRedirect is a ActivityTemplate of type redirect.
	// 外链活动
	ActivityTemplateRedirect ActivityTemplate = "redirect"
)

var ErrInvalidActivityTemplate = fmt.Errorf("not a valid ActivityTemplate, try [%s]", strings.Join(_ActivityTemplateNames, ", "))

var _ActivityTemplateNames = []string{
	string(ActivityTemplateArticle),
	string(ActivityTemplateRedirect),
}

// ActivityTemplateNames returns a list of possible string values of ActivityTemplate.
func ActivityTemplateNames() []string {
	tmp := make([]string, len(_ActivityTemplateNames))
	copy(tmp, _ActivityTemplateNames)
	return tmp
}

// ActivityTemplateValues returns a list of the values for ActivityTemplate
func ActivityTemplateValues() []ActivityTemplate {
	return []ActivityTemplate{
		ActivityTemplateArticle,
		ActivityTemplateRedirect,
	}
}

// String implements the Stringer interface.
func (x ActivityTemplate) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ActivityTemplate) IsValid() bool {
	_, err := ParseActivityTemplate(string(x))
	return err == nil
}

var _ActivityTemplateValue = map[string]ActivityTemplate{
	"article":  ActivityTemplateArticle,
	"redirect": ActivityTemplateRedirect,
}

// ParseActivityTemplate attempts to convert a string to a ActivityTemplate.
func ParseActivityTemplate(name string) (ActivityTemplate, error) {
	if x, ok := _ActivityTemplateValue[name]; ok {
		return x, nil
	}
	return ActivityTemplate(""), fmt.Errorf("%s is %w", name, ErrInvalidActivityTemplate)
}

// MustParseActivityTemplate converts a string to a ActivityTemplate, and panics if is not valid.
func MustParseActivityTemplate(name string) ActivityTemplate {
	val, err := ParseActivityTemplate(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x ActivityTemplate) Ptr() *ActivityTemplate {
	return &x
}

// MarshalText implements the text marshaller method.
func (x ActivityTemplate) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ActivityTemplate) UnmarshalText(text []byte) error {
	tmp, err := ParseActivityTemplate(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// DistributionStatusPending is a DistributionStatus of type pending.
	// 待发放
	DistributionStatusPending DistributionStatus = "pending"
	// DistributionStatusDistributing is a DistributionStatus of type distributing.
	// 发放中
	DistributionStatusDistributing DistributionStatus = "distributing"
	// DistributionStatusFailed is a DistributionStatus of type failed.
	// 发放失败
	DistributionStatusFailed DistributionStatus = "failed"
	// DistributionStatusSuccess is a DistributionStatus of type success.
	// 发放成功
	DistributionStatusSuccess DistributionStatus = "success"
)

var ErrInvalidDistributionStatus = fmt.Errorf("not a valid DistributionStatus, try [%s]", strings.Join(_DistributionStatusNames, ", "))

var _DistributionStatusNames = []string{
	string(DistributionStatusPending),
	string(DistributionStatusDistributing),
	string(DistributionStatusFailed),
	string(DistributionStatusSuccess),
}

// DistributionStatusNames returns a list of possible string values of DistributionStatus.
func DistributionStatusNames() []string {
	tmp := make([]string, len(_DistributionStatusNames))
	copy(tmp, _DistributionStatusNames)
	return tmp
}

// DistributionStatusValues returns a list of the values for DistributionStatus
func DistributionStatusValues() []DistributionStatus {
	return []DistributionStatus{
		DistributionStatusPending,
		DistributionStatusDistributing,
		DistributionStatusFailed,
		DistributionStatusSuccess,
	}
}

// String implements the Stringer interface.
func (x DistributionStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DistributionStatus) IsValid() bool {
	_, err := ParseDistributionStatus(string(x))
	return err == nil
}

var _DistributionStatusValue = map[string]DistributionStatus{
	"pending":      DistributionStatusPending,
	"distributing": DistributionStatusDistributing,
	"failed":       DistributionStatusFailed,
	"success":      DistributionStatusSuccess,
}

// ParseDistributionStatus attempts to convert a string to a DistributionStatus.
func ParseDistributionStatus(name string) (DistributionStatus, error) {
	if x, ok := _DistributionStatusValue[name]; ok {
		return x, nil
	}
	return DistributionStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidDistributionStatus)
}

// MustParseDistributionStatus converts a string to a DistributionStatus, and panics if is not valid.
func MustParseDistributionStatus(name string) DistributionStatus {
	val, err := ParseDistributionStatus(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x DistributionStatus) Ptr() *DistributionStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x DistributionStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *DistributionStatus) UnmarshalText(text []byte) error {
	tmp, err := ParseDistributionStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
