// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"fmt"
	"strings"
)

const (
	// PointStatusPending is a PointStatus of type pending.
	// 待发放
	PointStatusPending PointStatus = "pending"
	// PointStatusDistributing is a PointStatus of type distributing.
	// 发放中
	PointStatusDistributing PointStatus = "distributing"
	// PointStatusSuccess is a PointStatus of type success.
	// 发放成功
	PointStatusSuccess PointStatus = "success"
	// PointStatusFailed is a PointStatus of type failed.
	// 发放失败
	PointStatusFailed PointStatus = "failed"
)

var ErrInvalidPointStatus = fmt.Errorf("not a valid PointStatus, try [%s]", strings.Join(_PointStatusNames, ", "))

var _PointStatusNames = []string{
	string(PointStatusPending),
	string(PointStatusDistributing),
	string(PointStatusSuccess),
	string(PointStatusFailed),
}

// PointStatusNames returns a list of possible string values of PointStatus.
func PointStatusNames() []string {
	tmp := make([]string, len(_PointStatusNames))
	copy(tmp, _PointStatusNames)
	return tmp
}

// PointStatusValues returns a list of the values for PointStatus
func PointStatusValues() []PointStatus {
	return []PointStatus{
		PointStatusPending,
		PointStatusDistributing,
		PointStatusSuccess,
		PointStatusFailed,
	}
}

// String implements the Stringer interface.
func (x PointStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PointStatus) IsValid() bool {
	_, err := ParsePointStatus(string(x))
	return err == nil
}

var _PointStatusValue = map[string]PointStatus{
	"pending":      PointStatusPending,
	"distributing": PointStatusDistributing,
	"success":      PointStatusSuccess,
	"failed":       PointStatusFailed,
}

// ParsePointStatus attempts to convert a string to a PointStatus.
func ParsePointStatus(name string) (PointStatus, error) {
	if x, ok := _PointStatusValue[name]; ok {
		return x, nil
	}
	return PointStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidPointStatus)
}

// MustParsePointStatus converts a string to a PointStatus, and panics if is not valid.
func MustParsePointStatus(name string) PointStatus {
	val, err := ParsePointStatus(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x PointStatus) Ptr() *PointStatus {
	return &x
}

// MarshalText implements the text marshaller method.
func (x PointStatus) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *PointStatus) UnmarshalText(text []byte) error {
	tmp, err := ParsePointStatus(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
