// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"fmt"
	"strings"
)

const (
	// VoteValidValid is a VoteValid of type valid.
	// 有效
	VoteValidValid VoteValid = "valid"
	// VoteValidInvalid is a VoteValid of type invalid.
	// 无效
	VoteValidInvalid VoteValid = "invalid"
)

var ErrInvalidVoteValid = fmt.Errorf("not a valid VoteValid, try [%s]", strings.Join(_VoteValidNames, ", "))

var _VoteValidNames = []string{
	string(VoteValidValid),
	string(VoteValidInvalid),
}

// VoteValidNames returns a list of possible string values of VoteValid.
func VoteValidNames() []string {
	tmp := make([]string, len(_VoteValidNames))
	copy(tmp, _VoteValidNames)
	return tmp
}

// VoteValidValues returns a list of the values for VoteValid
func VoteValidValues() []VoteValid {
	return []VoteValid{
		VoteValidValid,
		VoteValidInvalid,
	}
}

// String implements the Stringer interface.
func (x VoteValid) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x VoteValid) IsValid() bool {
	_, err := ParseVoteValid(string(x))
	return err == nil
}

var _VoteValidValue = map[string]VoteValid{
	"valid":   VoteValidValid,
	"invalid": VoteValidInvalid,
}

// ParseVoteValid attempts to convert a string to a VoteValid.
func ParseVoteValid(name string) (VoteValid, error) {
	if x, ok := _VoteValidValue[name]; ok {
		return x, nil
	}
	return VoteValid(""), fmt.Errorf("%s is %w", name, ErrInvalidVoteValid)
}

// MustParseVoteValid converts a string to a VoteValid, and panics if is not valid.
func MustParseVoteValid(name string) VoteValid {
	val, err := ParseVoteValid(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x VoteValid) Ptr() *VoteValid {
	return &x
}

// MarshalText implements the text marshaller method.
func (x VoteValid) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *VoteValid) UnmarshalText(text []byte) error {
	tmp, err := ParseVoteValid(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
