// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package model

import (
	"fmt"
	"strings"
)

const (
	// UserTokenStateUnverified is a UserTokenState of type unverified.
	// 未验证
	UserTokenStateUnverified UserTokenState = "unverified"
	// UserTokenStateVerified is a UserTokenState of type verified.
	// 已验证
	UserTokenStateVerified UserTokenState = "verified"
	// UserTokenStateRevoked is a UserTokenState of type revoked.
	// 已撤销
	UserTokenStateRevoked UserTokenState = "revoked"
)

var ErrInvalidUserTokenState = fmt.Errorf("not a valid UserTokenState, try [%s]", strings.Join(_UserTokenStateNames, ", "))

var _UserTokenStateNames = []string{
	string(UserTokenStateUnverified),
	string(UserTokenStateVerified),
	string(UserTokenStateRevoked),
}

// UserTokenStateNames returns a list of possible string values of UserTokenState.
func UserTokenStateNames() []string {
	tmp := make([]string, len(_UserTokenStateNames))
	copy(tmp, _UserTokenStateNames)
	return tmp
}

// UserTokenStateValues returns a list of the values for UserTokenState
func UserTokenStateValues() []UserTokenState {
	return []UserTokenState{
		UserTokenStateUnverified,
		UserTokenStateVerified,
		UserTokenStateRevoked,
	}
}

// String implements the Stringer interface.
func (x UserTokenState) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x UserTokenState) IsValid() bool {
	_, err := ParseUserTokenState(string(x))
	return err == nil
}

var _UserTokenStateValue = map[string]UserTokenState{
	"unverified": UserTokenStateUnverified,
	"verified":   UserTokenStateVerified,
	"revoked":    UserTokenStateRevoked,
}

// ParseUserTokenState attempts to convert a string to a UserTokenState.
func ParseUserTokenState(name string) (UserTokenState, error) {
	if x, ok := _UserTokenStateValue[name]; ok {
		return x, nil
	}
	return UserTokenState(""), fmt.Errorf("%s is %w", name, ErrInvalidUserTokenState)
}

// MustParseUserTokenState converts a string to a UserTokenState, and panics if is not valid.
func MustParseUserTokenState(name string) UserTokenState {
	val, err := ParseUserTokenState(name)
	if err != nil {
		panic(err)
	}
	return val
}

func (x UserTokenState) Ptr() *UserTokenState {
	return &x
}

// MarshalText implements the text marshaller method.
func (x UserTokenState) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *UserTokenState) UnmarshalText(text []byte) error {
	tmp, err := ParseUserTokenState(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
